version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: genealogy_db
    environment:
      POSTGRES_DB: genealogy_tree
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: genealogy_api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: genealogy_tree
      TREE_DEPTH_LIMIT: 10

volumes:
  postgres_data: